# netlify.toml

[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
