# netlify.toml

[build]
  base = "frontend"                # The root directory of your React app (frontend/)
  publish = "frontend/dist"         # The directory containing the build output (frontend/dist)
  command = "npm run build"         # Build command for Vite
  functions = "frontend/netlify/functions"  # Optional: where Netlify functions are located

[[redirects]]
  from = "/*"                       # Redirect all routes to index.html
  to = "/index.html"                # For React Router to work
  status = 200                      # HTTP status 200 (success)
