# netlify.toml

[build]
  base = "frontend"            # Set base directory to frontend
  publish = "frontend/dist"     # Use dist for Vite's output folder
  command = "npm run build"     # Vite build command
  functions = "netlify/functions"  # Optional: For serverless functions

[[redirects]]
  from = "/*"                  # Redirect all routes
  to = "/index.html"           # Serve index.html for all routes
  status = 200                 # Status 200 means success
